### ISSUE TITLE
Support different source types

### ISSUE THREAD

**Issue by rubensworks** [comunica/jQuery-Widget.js#1]
Currently, only TPF hypermedia sources are required. Comunica also supports other types of sources, so support for this should be implemented here as well.

**Comment by rubensworks** [comment]
@RubenVerborgh Do you think we should implement this before the first Comunica release?

The easiest way of implementing this would be to add multiple dropdown fields, one for each source type. For example, while we now have a 'Choose datasources' dropdown, this could for example be changed to 'Choose hypermedia entrypoints', 'Choose SPARQL endpoints' and 'Choose RDF datasources'.

Alternatively, the dropdown could be enhanced with some kind of tagging mechanism for each datasource. Datasources are preconfigured with a certain tag (in this case hypermedia entrypoint). When the user adds new datasources, the tag has to be selected (this could default to a hypermedia entrypoint)

**Comment by RubenVerborgh** [comment]
> Do you think we should implement this before the first Comunica release?

No, functionally equivalent is fine!

> The easiest way of implementing this would be to add multiple dropdown fields, one for each source type. For example, while we now have a 'Choose datasources' dropdown, this could for example be changed to 'Choose hypermedia entrypoints', 'Choose SPARQL endpoints' and 'Choose RDF datasources'.

…and the nicest way is to do autodiscovery :wink:

1. If TPF controls present, then TPF.
2. If URI pattern like `/sparql`, or responds to `?query=SELECT%20*%20WHERE%20%7B%20%3Ca%3E%20%3Cb%3E%20%3Cc%3E%20%7D` then SPARQL endpoint.
3. Else, RDF datasource.

**Comment by mielvds** [comment]
> If URI pattern like /sparql, or responds to ?query=SELECT%20*%20WHERE%20%7B%20%3Ca%3E%20%3Cb%3E%20%3Cc%3E%20%7D then SPARQL endpoint.

I'd say use https://www.w3.org/TR/sparql11-service-description/ first!

**Comment by RubenVerborgh** [comment]
> I'd say use https://www.w3.org/TR/sparql11-service-description/ first!

Good point. Curious to know how common this is.

**Comment by mielvds** [comment]
It's not: http://www.heikopaulheim.com/docs/iswc2013_poster.pdf

**Comment by RubenVerborgh** [comment]
So not having a description is a better prediction of being a SPARQL endpoint than having one? :-D Well, I suppose we should take into account the prior chance of something being a SPARQL endpoint in the first place.

**Comment by mielvds** [comment]
A waterfall is best: Service Description (it is a standard) -> query response -> url

**Comment by RubenVerborgh** [comment]
Agree with waterfall, but would have URL on second place (as it saves a request). URL is redundant after query response, which is a conclusive test.

**Comment by RubenVerborgh** [comment]
BTW @rubensworks, searching for TPF controls or Service Descriptions in a response, can we do this using the SPARQL engine itself?

**Comment by rubensworks** [comment]
Autodiscovery using a waterfall system sounds good!

> BTW @rubensworks, searching for TPF controls or Service Descriptions in a response, can we do this using the SPARQL engine itself?

I haven't tested it yet, but that _should_ be possible. It might lead to some cyclic dependencies, but that should not cause any issues. (It might be good to have a pre-built SPARQL engine config that can work directly on RDF streams for this)

**Comment by RubenVerborgh** [comment]
> I haven't tested it yet, but that should be possible.

I'd really want it at some point; I've never liked https://github.com/LinkedDataFragments/Client.js/blob/v2.0.5/lib/extractors/ControlsExtractor.js#L67

**Comment by rubensworks** [comment]
Yeah, that's how comunica does it as well at the moment.

I do think that the current implementation will be the most efficient though.

But as this logic is contained in a separate actor, we can easily implement a different actor for this, that does controls extraction based on a SPARQL query, and test its performance :-) (Will make an issue for this, as we're getting off-topic here)

**Comment by RubenVerborgh** [comment]
> I do think that the current implementation will be the most efficient though.

Efficient, yes, but it does not catch all cases.

**Comment by rubensworks** [comment]
Closing this, as this was enabled a while ago in fb42425dc73421bf00fb7389924849faa52faa72.
