### ISSUE TITLE
Communica-compile-config

### ISSUE THREAD

**Issue by kabulkurniawan** [comunica/jQuery-Widget.js#10]
getting this error message during running "yarn install" on my ubuntu 18.04.1 LTS
so, the installation was failed

/bin/sh: 1: comunica-compile-config: not found
error Command failed with exit code 127.

**Comment by kabulkurniawan** [comment]
Well, the latest repo was successfully installed. thanks :)

**Comment by rubensworks** [comment]
This is fixed as of 996bec310b4f53f3db6c094f0eaec09ed937658c
