### ISSUE TITLE
Multiple http://query.linkeddatafragments.org/ examples don't work in Firefox, but keep working in eg Chrome

### ISSUE THREAD

**Issue by bjdmeest** [comunica/jQuery-Widget.js#101]
See eg http://query.linkeddatafragments.org/#transientDatasources=%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen;https%3A%2F%2Fruben.verborgh.org%2Fprofile%2F&query=SELECT%20%3Fperson%20%3Fdate%0AWHERE%20%7B%0A%20%20ruben%3Ame%20dbpedia-owl%3AbirthPlace%20%3Fplace%3B%0A%20%20%20%20%20%20%20%20%20%20%20dbpedia-owl%3AbirthDate%20%20%3FdateR.%0A%20%20%3Fperson%20%20dbpedia-owl%3AbirthPlace%20%3Fplace%3B%0A%20%20%20%20%20%20%20%20%20%20%20dbpedia-owl%3AbirthDate%20%20%3Fdate.%0A%20%20FILTER(%3Fdate%20%3E%20%3FdateR)%0A%7D

In firefox, I get CORS blocked errors like on `https://data.linkeddatafragments.org/viaf. (Reason: CORS request did not succeed).` (both HTTP and https)

I assumed https://newbedev.com/firefox-cross-origin-request-blocked-despite-headers would solve the issue, but doing the suggested action "You can do this by visiting the blocked link once and addibng the exception." didn't help

**Comment by rubensworks** [comment]
Probably related to https://github.com/comunica/comunica/commit/a96547be4b112887a4e164496e2c6540737d8391
If we can't fix this one easily, we may consider going back to the native HTTP actor (for Firefox).
