### ISSUE TITLE
this module requires vulnerable sub dependencies via deprecated yasgui-yasqe@2.11.22 dependency

### ISSUE THREAD

**Issue by phivk** [comunica/jQuery-Widget.js#114]
we deploy a [web client](https://cat.apis.beeldengeluid.nl/), generated via this module with some custom queries and settings, see [this repo](https://github.com/beeldengeluid/comunica-web-client).

I noticed several dependabot security alerts caused by this module's dependency `yasgui-yasqe@2.11.22`. 
When I checked [its repo](https://github.com/YASGUI/YASQE), I found out it is deprecated in favour of https://github.com/TriplyDB/Yasgui.

Not sure how straightforward it is to replace `yasgui-yasqe` with `@triply/yasgui` in terms of compatibility, but it seems desirable.

**Comment by rubensworks** [comment]
Oh, I wasn't aware of the package rename, thanks for reporting!

I guess this should be just a matter of renaming the usages of yasgui here.
Feel free to submit a PR for it if you're up for it.

**Comment by phivk** [comment]
> I guess this should be just a matter of renaming the usages of yasgui here.

I am giving this a try but am running into some issues with importing the CSS. 
I will create a draft PR to discuss.

**Comment by phivk** [comment]
see this PR: https://github.com/comunica/jQuery-Widget.js/pull/116
