### ISSUE TITLE
Run container as Non-root User

### ISSUE THREAD

**Issue by MPParsley** [comunica/jQuery-Widget.js#129]
By default, Docker runs commands inside the container as root which violates the [Principle of Least Privilege (PoLP)](https://en.wikipedia.org/wiki/Principle_of_least_privilege) when superuser permissions are not strictly required. You want to run the container as an unprivileged user whenever possible. The node images provide the node user for such purpose.

https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user

**Comment by rubensworks** [comment]
Sure!
A PR is definitely welcome on this.

Related to https://github.com/comunica/comunica/pull/944
