### ISSUE TITLE
Support Solid authentication

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/jQuery-Widget.js#26]
Now that we have https://github.com/comunica/actor-http-solid-auth-fetch, we could add a "login" button to the query client.

However, solid-auth-client is rather big, so we might only want to load it if "login" is actually clicked.

The interesting consequence here is that some queries will have fewer results when logged out, and more when logged in.

**Comment by rubensworks** [comment]
Was done in acb035a112918326548c56ee8bd223dac942e0eb
