### ISSUE TITLE
Invalid syntax error on initial page load

### ISSUE THREAD

**Issue by RubenVerborgh** [comunica/jQuery-Widget.js#35]
On initial page load of http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Flinked.open.gent%2Fparking&query=SELECT%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D%0ALIMIT%20100, I get:

```
Parse error on line 14:
...g/ontology/>SELECT WHERE {  ?s ?p ?o.
----------------------^
```

Seems like concatenation gone wrong. (I also wonder to what extent we need this concatenation, since YASGUI automatically adds prefixes.)

**Comment by rubensworks** [comment]
Isn't that just an invalid query?

This query does not give any parse errors for me: http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Flinked.open.gent%2Fparking&query=SELECT%20*%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D%0ALIMIT%20100

**Comment by RubenVerborgh** [comment]
It most definitely is.
