### ISSUE TITLE
Docker container build fails

### ISSUE THREAD

**Issue by dpancic** [comunica/jQuery-Widget.js#56]
Step 4/8 : RUN cd ${dir} && npm install --unsafe-perm
 ---> Running in e0c6fb523108

npm WARN notice [SECURITY] jquery has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=jquery&version=2.2.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @comunica/actor-abstract-bindings-hash@^1.9.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@comunica/actor-query-operation-distinct-hash'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-16T13_40_43_625Z-debug.log
Removing intermediate container e0c6fb523108
The command '/bin/sh -c cd ${dir} && npm install --unsafe-perm' returned a non-zero code: 1
    Build failed

**Comment by rubensworks** [comment]
This seems to be caused by a Comunica update I just did.
It looks like npm is having some caching issues, because I'm seeing similar problems when installing recently updated packages myself.

Let's wait and see what happens when npm caches invalidate.

**Comment by dpancic** [comment]
Yes, it is working. The Docker container build works. Thank you
