### ISSUE TITLE
Access Token Configuration

### ISSUE THREAD

**Issue by KakoozaJerry** [comunica/jQuery-Widget.js#91]
In order to use tiles from Mapbox, you must also request an [access token](https://www.mapbox.com/studio/account/tokens/).
These can be obtained from [Mapbox access](https://docs.mapbox.com/help/glossary/access-token/) documentation.

We want to;

- [ ] Make the access token configurable from the `settings.json` file
- [ ] Have the token accessed and used within the `src/ldf-client-ui.js` file [line 117](https://github.com/KakoozaJerry/jQuery-Widget.js/blob/21f716776139aa0ea8968aef1e599957c34bf912/src/ldf-client-ui.js#L117)

**Comment by rubensworks** [comment]
Done in https://github.com/comunica/jQuery-Widget.js/commit/5fe3e94f38bca23533daaf0890ca91a19abb1f2d
