### ISSUE TITLE
Resizing text area breaks vertical layout

### ISSUE THREAD

**Issue by KasperZutterman** [comunica/jQuery-Widget.js#95]
When you resize the query and/or context text area, it visually breaks the vertical layout.
This can be prevented by making the text areas only vertically resizable.
![image](https://user-images.githubusercontent.com/21260838/125913295-25e38788-e97d-465a-8192-09696b172121.png)

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €136 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
A bounty has been placed on this issue via the Comunica Association (see original post).
